name: "Install Python env using UV"
description: "Installs Python environment using UV package manager"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Load cached venv
      id: cached-uv-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

    - name: Load cached UV cache
      id: cached-uv-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: uvcache-${{ runner.os }}-${{ hashFiles('uv.lock') }}

    - name: Install UV Package Manager
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.17"
        enable-cache: true

    - name: Install dependencies
      shell: bash
      if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
      run: uv sync --all-extras --dev

    - name: Activate environment
      shell: bash
      run: source .venv/bin/activate
