# Generated by Django 5.2.7 on 2025-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('sponsorship_date', models.DateField(blank=True, null=True)),
                ('sponsor_type', models.CharField(choices=[('KEYSTONE', 'Keystone'), ('PLATINUM', 'Platinum'), ('TITANIUM', 'Titanium'), ('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['name'],
            },
        ),
    ]
