# Generated by Django 5.2.7 on 2026-01-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_alter_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='platinum_category',
            field=models.CharField(blank=True, choices=[('SPONSOR', 'Sponsor'), ('PARTNER', 'Partner')], help_text='Select the Platinum category for this sponsor', max_length=50, null=True),
        ),
    ]
