# Generated by Django 5.2.7 on 2025-10-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='SpeakerPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('presentation_type', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('panel', 'Panel')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='speakers.speaker')),
            ],
            options={
                'verbose_name': 'Speaker Presentation',
                'verbose_name_plural': 'Speaker Presentations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('day_1', 'Day 1'), ('day_2', 'Day 2')], max_length=255)),
                ('track', models.CharField(choices=[('track_1', 'Track 1'), ('track_2', 'Track 2'), ('track_3', 'Track 3')], max_length=255)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='speakers.speakerpresentation')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='speakers.speaker')),
            ],
            options={
                'verbose_name': 'Speaker Schedule',
                'verbose_name_plural': 'Speaker Schedules',
            },
        ),
        migrations.CreateModel(
            name='SpeakerSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='speakers.speaker')),
            ],
            options={
                'verbose_name': 'Speaker Social',
                'verbose_name_plural': 'Speaker Socials',
                'ordering': ['platform'],
            },
        ),
    ]
